### ISSUE TITLE
Hybrid Obj-c/ Swift app

### ISSUE THREAD

**Issue by n8stowell82** [preemptive/PPiOS-Rename#1]
This isn't so much a bug but a question.  How will this tool handle a hybrid Obj-c/Swift application?  Can swift code be obfuscated as well? If not is it just ignored by default, or would I need to manually setup an ignore file of sorts?

Thanks in advance for your time

**Comment by truist** [comment]
We haven't really tested Swift apps. You might be able to compile a hybrid app by excluding all the names in the Swift code, and the Objective-C names directly referenced by the Swift code - but you'd have to try it to be sure. This approach definitely won't work for obfuscating the Swift code; Swift doesn't have the preprocessor macro support that this solution is based on.
