### ISSUE TITLE
Error when running on simulator

### ISSUE THREAD

**Issue by zahidgu** [preemptive/PPiOS-Rename#11]
Hi, 

I followed the instructions to use PPiOS-Rename in order to obfuscate the source code of my iOS App. As per the instructions mentioned in the guide, I created two additional targets Build and analyze and Apply Renaming. I followed the below steps:

1- Build using Build and analyze target
2- Build using Apply Renaming target
3-Finally build using the original target

All 3 were build successfully without any errors. However when I run the application on the simulator after the step 3 above, I get the following error for my view controller:

```

Terminating app due to uncaught exception 'NSUnknownKeyException'
[<StartupViewController 0x7fb5a6515510> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key y4feaiGk
```

Upon inspecting the y4feaiGk, its assigned to a UIButton in the corresponding xib file. 
If i exclude the above view controller, the error comes up in the next ViewController. 

I will appreciate any help as I am unsure what is going wrong over here. Thanks a lot!

**Comment by neuralmer** [comment]
Renaming that *PPiOS-Rename* applies can cause conflicts with KVO, specifically making a project no longer key value coding-compliant.  Please ensure that you have updated KVO references as described in [README.md](https://github.com/preemptive/PPiOS-Rename#key-value-observing-kvo).

If this does not fix the problem, please reopen this issue.
