### ISSUE TITLE
Notice: Is there a solution?

### ISSUE THREAD

**Issue by safiriGitHub** [preemptive/PPiOS-Rename#15]
如果你的APP打算发布到App Store，切勿用代码混淆。 会被无情驳回且延期审核/(ㄒoㄒ)/~~
If your APP is going to be published to the APP Store, don't confuse code. It will be ruthlessly rejected and delayed.

Guideline 2.3.1 - Performance

We discovered that your app contains hidden features. Specifically, It would be appropriate to remove all code obfuscation and selector mangling or to explain in detail the purpose of its inclusion before resubmitting for review.

**Comment by truist** [comment]
Most apps seem to be accepted by the Apple without raising this issue, but we have heard some feedback like this from our users. We have not been able to reproduce the issue ourselves, with our apps. 

Some users have had success by either doing what they ask ("explain in detail the purpose of its inclusion") or by sending them the PPiOS `symbols.map` so they can translate the code themselves, or both. 

If you try either of those, please let us know the results; we continue to try to understand Apple's behavior in these cases.

**Comment by safiriGitHub** [comment]
O__O "…I have submitted the review again,I should ask for your advice in advance,sorry. Now,I'm afraid to test in my  main app, because apple delay review and warn me to stop my account when i make this mistake again . After when use other account and app to test.
