### ISSUE TITLE
Uncaught exception crash (in obfuscated app)

### ISSUE THREAD

**Issue by sidan5** [preemptive/PPiOS-Rename#16]
I have this when loading a new view controller:

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UITableView (<UITableView: 0x7fb7b318a000; frame = (0 0; 375 812); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x604000a4d5c0>; layer = <CALayer: 0x604000829c40>; contentOffset: {0, -88}; contentSize: {375, 132}; adjustedContentInset: {88, 0, 34, 0}>) failed to obtain a cell from its dataSource (<_UIFilteredDataSource: 0x604000a4d0e0>)'`

Tried and solved some with https://github.com/preemptive/PPiOS-Rename/issues/3 but still having this in many parts of the code. Any solution?

**Comment by neuralmer** [comment]
As discussed in #17, I would need additional detail to help diagnose this issue.

**Comment by neuralmer** [comment]
Closing for now. Please provide additional detail if you reopen this issue.
