### ISSUE TITLE
Preventing common rejection from App Review

### ISSUE THREAD

**Issue by justAnIndieDeveloper** [preemptive/PPiOS-Rename#19]
Apple would reject an app using this library straight forward for that reason:

> From Apple 2. 3 Performance: Accurate Metadata Guideline 2.3.1 - Performance
> 
>     We discovered that your app contains hidden features. Specifically, It would be appropriate to remove all code obfuscation and selector mangling from this app before resubmitting for review.
> 
>     The next submission of this app may require a longer review time.
> 
>     Next Steps
> 
>         Review the Performance section of the App Store Review Guidelines.
>         Ensure your app is compliant with all sections of the App Store Review Guidelines and the Terms & Conditions of the Apple Developer Program.
>         Once your app is fully compliant, resubmit your app for review.
> 
>     Submitting apps designed to mislead or harm customers or evade the review process may result in the termination of your Apple Developer Program account. Review the Terms & Conditions of the Apple Developer Program to learn more about our policies regarding termination.
> 
>     If you believe your app is compliant with the App Store Review Guidelines, you may submit an appeal. Alternatively, you may provide additional details about your app by replying directly to this message.
> 

I thought of replacing the random numbers on symbols.map file into some dictionary words. And then run the obfuscation code (using the new created symbols).

What I wanted to know is if the obfuscation process change anything further then those names to random number that could look "strange" on the binary? What I mean is that if instead of random numbers I would use some English words would the binary have anything else that would point that the app uses obfuscation?

**Comment by justAnIndieDeveloper** [comment]
@truist @neuralmer Can you help here?

**Comment by truist** [comment]
Most apps seem to be accepted by the Apple without raising this issue, but we have heard some feedback like this from our users. We have not been able to reproduce the issue ourselves, with our apps.

Some users have had success by either doing what they ask ("explain in detail the purpose of its inclusion") or by sending them the PPiOS symbols.map so they can translate the code themselves, or both.

If you try either of those, please let us know the results; we continue to try to understand Apple's behavior in these cases.

**Comment by justAnIndieDeveloper** [comment]
So, Technically if instead or random numbers on the map file there would be words would there be any other "trace" for obfuscation? Just want to figure this out.

**Comment by justAnIndieDeveloper** [comment]
@truist Do you know if PPiOS-rename change anything in the binary besides replacing names as on the symbols.map file? Thanks!

**Comment by neuralmer** [comment]
@justAnIndieDeveloper *PPiOS-Rename* only does renaming, and only applies the renamings as they appear in the `symbols.map` file. There are only two ways that it changes the app: renaming identifiers by means of `#define`s in `symbols.h`, and by directly changing symbols in the .xib/storyboard files.

If they accept the app with a `symbols.map` with garbage names rather than randomly generated names, then that would suggest that they are only rejecting the app when it is clear that obfuscation was applied.

**Comment by haihw** [comment]
We did appeal successfully once by giving the reviewer the symbols.map file. But it's only case by case. There is other team also did the same way and still got rejected. 
 
Can PPiOS-rename allow to set the custom dictionary map instead of alway randomly generates name?

**Comment by neuralmer** [comment]
You could alter the contents of the `symbols.map` file before applying renaming, but there is otherwise no means to control the renamings.
