### ISSUE TITLE
Obfuscating framework

### ISSUE THREAD

**Issue by klipa-dev** [preemptive/PPiOS-Rename#2]
Just wanted to know is it possible to obfuscate just framework? Because when I do analyze my framework it returns empty symbol.map file. Best regards

**Comment by truist** [comment]
Today, the way we identify renaming exclusions treats a standalone framework as something to be excluded - so it doesn't get renamed. We will be making it possible to obfuscate a standalone framework, but we don't have a firm ETA yet.

**Comment by CodeLife2012** [comment]
Any update?

**Comment by truist** [comment]
@nklipa13 @CodeLife2012 this feature has been in development and the release is in the final QA stages. We're hoping to publish next week. (Along with an updated [PPiOS-ControlFlow](https://www.preemptive.com/products/ppios).)

**Comment by jcayzac** [comment]
Great news! I've been waiting for this for a long time. Now with visibility=hidden for all the C/C++ stuff and PPiOS for the ObjC stuff I can finally add 3rd-party frameworks to my own frameworks without running the risk to conflict with versions of those same libraries used in apps consuming my framework 🎉 

(actually visibility-hidden already works fine for ObjC too, but the ObjC runtime *still* very stupidly logs a warning saying regarding undefined behavior …that is pretty much defined 🤔 )

**Comment by neuralmer** [comment]
[Version 1.1.0](https://github.com/preemptive/PPiOS-Rename/releases/tag/v1.1.0) has been released.  This version provides support for obfuscating dynamic frameworks, please see [Analyzing Frameworks](https://github.com/preemptive/PPiOS-Rename#analyzing-frameworks) in the documentation.

**Comment by gauravmb** [comment]
i am unable to obfuscate framework,  build with Swift and objective C

**Comment by neuralmer** [comment]
*PPiOS-Rename* does [not support Swift](https://github.com/preemptive/PPiOS-Rename#supported-platforms).

**Comment by VladPodvoiskyi** [comment]
PPiOS-Rename doesnt rename class and function name(((
