### ISSUE TITLE
PPiOS-ControlFlow Source/Download

### ISSUE THREAD

**Issue by ParityError** [preemptive/PPiOS-Rename#20]
I'm looking for the ControlFlow utility mentioned in your `README.md`, although came up empty locating it. 
```
It is possible to reverse the process of obfuscation in dSYMs by using a utility included with PPiOS-ControlFlow. 
```
Where can I obtain this tool? Thank you.

**Comment by truist** [comment]
PPiOS-ControlFlow was a commercial obfuscation tool that we sold alongside PPiOS-Rename. We have stopped updating and selling that tool, so the dSYM utility is no longer available. We will update our documentation accordingly, soon.
