### ISSUE TITLE
Error: PPiOS-Rename cannot process apps containing Swift code

### ISSUE THREAD

**Issue by euroboy** [preemptive/PPiOS-Rename#21]
My Objective C project uses a cocoapod written in swift, and I'm getting the next error:
`Error: PPiOS-Rename cannot process apps containing Swift code`
I know that PPiOS-Rename doesn't support Swift, but is there a way to filter swift files? Thanks.

**Comment by truist** [comment]
Sorry, no. The library we use to parse binaries doesn't handle Swift code, so once we encounter it we can't be sure that the result of our analysis is correct, and/or that the exclusions that you supply would actually be applied correctly.
