### ISSUE TITLE
What's the purpose on inverting symbols dict before writing symbols map?

### ISSUE THREAD

**Issue by kenny1269** [preemptive/PPiOS-Rename#22]
In the method -[CDSymbolMapper writeSymbolsFromSymbolsVisitor:toFile:], you invert the symbols dict before writing it to symbols.map, and then invert it again after reading from the symbols.map. I am wendering about this.

**Comment by neuralmer** [comment]
You are right that it would make more sense to not invert the map in the first place. Historically the map was inverted, and there was never a point where we wanted to spend the effort and accept confusion caused by changing it (versioning, backward-compatibility, etc.).
