### ISSUE TITLE
Unknown class error in Interface Builder file AGAIN

### ISSUE THREAD

**Issue by surfingtomchen** [preemptive/PPiOS-Rename#23]
I understand there is an issue about this issue #6 , but my situation is quite different.

I have used Xcode run script method to obfuscate the Objective-c code on Xcode 10.1. Project can be build. But the app crashes upon launch due to xib file key value coding-compliant.

Unknown class v7aeUe4E in Interface Builder file

this  class is a UIView subclass, and the v7aeUe4E **DO EXISTS** in the symbol.h with corrent class name

Please advice me on this. Thanks a lot, it costed me 4 hours and didn't find any solution.

**Comment by surfingtomchen** [comment]
Now I find that if a xib has custom class, the load of custom class will be failed if it was renamed. Is that the Xcode 10 change the way to load nib in the dynamic running period or in compile process?

**Comment by neuralmer** [comment]
Please read my response to Issue 17: https://github.com/preemptive/PPiOS-Rename/issues/17#issuecomment-402188567

It sounds like you have already determined that it is not an issue of category 1 or 3 from that list, and I suspect you could be seeing category 2: the prefix .pch file is not being included when your class is being compiled. Please see [this](https://github.com/preemptive/PPiOS-Rename#missing-pch-file) troubleshooting entry.

**PPiOS-Rename** is not able to figure out if it has found all of the .pch files that it needs to or determine if configuration in Xcode needs to be changed to include additional .pch files, and thus it only emits an error if it cannot find any .pch files.

**Comment by neuralmer** [comment]
Closing. If this does not address the issue you are seeing, please reopen and provide any clarifying details.
