### ISSUE TITLE
Shows Build Failed: Error in Protobuf (pod)

### ISSUE THREAD

**Issue by mobisidd** [preemptive/PPiOS-Rename#25]
Hi,
I followed all the steps as mentioned but at the end of all the steps i got the following error.

https://imgur.com/a/iQxRz7f

**Comment by neuralmer** [comment]
It looks like you're working with a project that is composing identifiers from other identifiers. The approach *PPiOS-Rename* uses for renaming may not work so well with that. You will need to exclude the identifiers that are being modified.

Our renaming is doing something like:
```
someIdentifier -> n55eXqqq
```

And some of your code is looking for `SomethingsomeIdentifierSomethingElse` and not finding it, but instead finding `Somethingn55eXqqqSomethingElse`.

**Comment by mobisidd** [comment]
That makes sense. How can i exclude the identifiers or may be we can exclude whole POD folder ?

**Comment by neuralmer** [comment]
Assuming that the Pod follows the naming convention of prefixing everything with a 2-3 letter code, all of the symbols can be excluded using a pattern as described in the read me [here](https://github.com/preemptive/PPiOS-Rename#filter-classes-protocols-andor-categories).
