### ISSUE TITLE
Missing .pch file

### ISSUE THREAD

**Issue by jjh8326** [preemptive/PPiOS-Rename#30]
I followed the trouble shooting steps and auto generated my own pch file, I named the file accordingly yet I still get the error “Couldn’t find any *-Prefix.pch files under .” - what am I doing wrong? I followed all the instructions and i have configured my build settings to us the pch file as well.

**Comment by neuralmer** [comment]
Sorry for the delayed response.

We'll need more information about what you're doing to fix the issue. What is the name of your pch file? Where is the file relative to the project?

**Comment by jjh8326** [comment]
Thank you for the response, the pch file is named Demo-Prefix.pch. This file is located in the "Demo" folder, and the "Demo" folder is located in the same place as the .xcodeproj file.

**Comment by neuralmer** [comment]
What version of Xcode are you using? You're using PPiOS-Rename 1.3? What OS version? This project is strictly Objective-C?

**Comment by neuralmer** [comment]
Closing this for now. If you are still having this issue, please reopen the issue and provide more details about what is going on.
