### ISSUE TITLE
Using Obfuscated framework

### ISSUE THREAD

**Issue by hilamt** [preemptive/PPiOS-Rename#32]
I am trying to obfuscate my code which includes dynamic framework.
I don't want to exclude the framework because then the binary contains unobfuscated functions from the framework. 
Is there a way to do it?

I tried to obfuscate my code with my linked framework and I got the error:  **Use of undeclared identifier {framwork}**
I tried to obfuscate my code with my linked framewor, which was already obfuscated (added the symbols.h file to the *.pch file ) and I got the error:**Undefined symbol: _OBJC_CLASS_$_{framwork}**

I ran out of ideas, can you help me?

**Comment by neuralmer** [comment]
Do you have the sources for the dynamic framework, or is this a closed-source third party framework?

**Comment by hilamt** [comment]
I have the source

**Comment by neuralmer** [comment]
Ok, I might need more information about how you are obfuscating and what is and isn't happening.

I think you should be able to obfuscate both parts by:
1. Analyzing the app (e.g. you don't need to create a synthetic app to analyze for the dynamic library, you already have an app)
2. Obfuscating the app by making sure that it uses the `*-Prefix.pch` file.
3. Obfuscating the dynamic framework by making sure that it also uses a `*-Prefix.pch` file, even if it is a different one from that of the app. The name of the file needs to have that format.
4. Sorting out what symbols need to be excluded. This might mean excluding `xxx` if you see something like `Undefined symbol: OBJC_CLASS$_xxx`, though `{framwork}` doesn't look like a real symbol.

If this doesn't help, please give more details about your configuration.

**Comment by neuralmer** [comment]
Closing this issue for now. Please reopen this issue if you are still working with this issue and can provide more details.
