### ISSUE TITLE
 xcframework obfuscation

### ISSUE THREAD

**Issue by RanaSaleh** [preemptive/PPiOS-Rename#33]
Hi, 
Please I have an XCFramework  and I am using PPIOS for obfuscation,
I execute the following instructions to do that:
a-ppios-rename --analyze --framework ProjectName /path/to/framework/executable
b-ppios-rename --obfuscate-sources
I successfully create symbol.map and symbols .h but the clients are still able to access and read all functions , how can I build this framework before drop it inside another project.?

Or in another way , if I have an Xcode project created as framework , I obfuscate this project as you mentioned how can I generate now the xcframework from this obfuscated code?

The obfuscation should be done before or after creating the xcframework?

Your help is really appreciated.

Regards

**Comment by neuralmer** [comment]
Did you follow the instructions for [project setup](https://github.com/preemptive/PPiOS-Rename#project-setup), allowing for the framework-specific details [here](https://github.com/preemptive/PPiOS-Rename#analyze-dynamic-frameworks).

The obfuscation should be done before creating the XCFramework. Your XCFramework is a binary framework, you're not shipping sources, right?

Are the renamings that are in symbols.h [being applied](https://github.com/preemptive/PPiOS-Rename#verify-obfuscation) to your `.framework` before assembling the XCFramework? If you are not seeing them being applied, then it is almost certainly an issue with the precompiled header not being included, see this topic in [troubleshooting](https://github.com/preemptive/PPiOS-Rename#missing-pch-file).

**Comment by neuralmer** [comment]
I'm closing this for now. If the links I mentioned did not fix the issue for you, please reopen this issue with more details of the problem.
