### ISSUE TITLE
About small methods , can not dump the instanceMethod name and types .

### ISSUE THREAD

**Issue by MrLeeSr** [preemptive/PPiOS-Rename#34]
After merge [this](https://github.com/nygard/class-dump/pull/103) change , i can get the class but i can not dump the small method name and types . 

debug info : in CDObjectiveC2Processor.m , when i try to get a class instance method ,
            objc2Method.name  = [cursor readPtr:small];
            objc2Method.types = [cursor readPtr:small];
            objc2Method.imp   = [cursor readPtr:small];
            NSString *name    = [self.machOFile stringAtAddress:objc2Method.name];
            NSString *types   = [self.machOFile stringAtAddress:objc2Method.types];
i got a nil value .  All the instance method is this . It look like the offset or mask did not right .

**Comment by neuralmer** [comment]
Are you seeing this issue with a standard framework/library? If so which one? Or, are you otherwise able to provide a reproduction?

**Comment by MrLeeSr** [comment]
Thanks for reply , i got this problem which in a new project demo created in Xcode12  . I put it in this [respository](https://github.com/MrLeeSr/SmallMethodDemo/tree/master) .  When you try to get the instance method of 'ViewController' or 'LBObj' , you will get this issue . or you can create a new on use Xcode12 and get a Test.

**Comment by neuralmer** [comment]
I meant to say here that I don't presently have time to take a look at this. I will as time permits.

**Comment by neuralmer** [comment]
I am able to reproduce the issue.

**Comment by neuralmer** [comment]
It looks like there is a layer of indirection that is not being interpreted correctly. The pointers are being interpreted as pointing into `__PAGE_ZERO`. It looks like the method name pointers should be pointing into `__DATA`/`__objc_selrefs`, possibly being offset by 0x100000000, and the data at that location is the address of the name. Similarly for the types, but I don't know which segment/section they are pointing to right now. I don't have time to continue working on this, unfortunately.
