### ISSUE TITLE
Swift Support

### ISSUE THREAD

**Issue by CoolHandLuke88** [preemptive/PPiOS-Rename#4]
Does this work with Swift 3?

**Comment by truist** [comment]
Sorry, no. This product only works with Objective C.

**Comment by wgrand** [comment]
Is this still the case now that it's 2018? Why would the tool only work with Objective-C?

**Comment by neuralmer** [comment]
It is still the case. Swift does not support Objective-C `#define` preprocessor directives, and that is fundamental to the approach that *PPiOS-Rename* uses for renaming.
