### ISSUE TITLE
Unknown class error in Interface Builder file

### ISSUE THREAD

**Issue by smartsanja2013** [preemptive/PPiOS-Rename#6]
I have used Xcode run script method to obfuscate the Objective-c code on Xcode 8.3.3. Project can be build. But the app crashes upon launch due to story board key value coding-compliant.

`Unknown class s3YfbbAX in Interface Builder file`

I am getting 5 `Unknown class xxxxxxx in Interface Builder file` errors. All those 5 are not external libraries which provide Interface Builder files. 
Instead those 5 are the root view controllers (TabbarController and 4 UIViewControllers).

Problem is, I cannot find `s3YfbbAX` in the `symbols.h` file. I can see this key in the story board. But, in `symbols.h` has a different key for the equivalent Class name.

Please advice me on this

**Comment by neuralmer** [comment]
*PPiOS-Rename* currently renames identifiers in code via preprocessor `#define` statements, but Storyboards and `.xib` files are _altered directly_.  It sounds like the results of a prior obfuscate-sources phase were not reverted prior to the last renaming attempt.  I would expect the same errors to now be produced if you tried to build without renaming.

If this is the case, then you need to get your Storyboards/`.xib` files back to the state they were in prior to running the renaming-related targets (e.g. via source control).  *PPiOS-Rename* does not currently have a means to check that the Storyboards/`.xib` files are in the expected state when renaming is applied.

If something else appears to be going on, please reopen this issue with additional detail.
