### ISSUE TITLE
Error during obfuscation process 

### ISSUE THREAD

**Issue by jeremiasdsa** [preemptive/PPiOS-Rename#8]
Hi everyone,

I'm facing this error message. Can you help me to solve it?  

> error: no visible @interface for 'MyManager' declares the selector 'setC1OpVkNd:'
>     [[MyManager sharedInstance] setPublicKey: pulicKey];

**Comment by neuralmer** [comment]
Your map file very likely contains a renaming from `setPublicKey` to `setC1OpVkNd`, and the code shown in the error is affected by the renaming (e.g. the `*-Prefix.pch` file that it is compiled with has included the `symbols.h`), but the code that defines `-[MyManager setPublicKey:]` is not.

There are a few possible reasons for this which include: `MyManager` is defined in a library and is not being compiled with this project, `MyManager` is being compiled but without a modified `.pch` file, `MyManager` is being compiled in a Pod but the Pod doesn't define a `.pch` file that matches the pattern, etc.  So either pre-compiled header file configuration in Xcode needs to be adjusted (the name must match `*-Prefix.pch`), or the `MyManager` class needs to be excluded as described for undefined symbols as described in [README.md](https://github.com/preemptive/PPiOS-Rename#undefined-symbols--exclusions).
