### ISSUE TITLE
Error when OBFUSCATE with SDK 11.0 XCode 9.0

### ISSUE THREAD

**Issue by neuralmer** [preemptive/PPiOS-Rename#9]
Originally posted [here](https://github.com/Polidea/ios-class-guard/issues/64) by [renlix](https://github.com/renlix):
> Hello Nathan, I'm starting to use PPIOS-Rename according to you, but I'm facing some problems.
I run the commands: "ppios-rename --analyze -x IgnoredSymbol -F !ExcludedClass -F !FBS* -F !FIR* -F !ModalSMSCredito* -F !GAI* -F !GGL* -F !Branch* /Desktop/Projetos/IOS/appPontoCerto//DerivedData/Build/Products/Debug-iphoneos/XXXXX.app" and "ppios-rename --obfuscate-sources".
But when I build my project, I get a lot of mistakes in relation to the 'FBSDK'(Facebook), 'FIRA'(Firebase), in my class 'ModalSMSCredito' and so on.
It is as if all the options "-F !YYY*" were ignored, and all were included in the obfuscation.

**Comment by neuralmer** [comment]
In `README.md` when discussing [filters](https://github.com/preemptive/PPiOS-Rename#filter-classes-protocols-andor-categories) and [command-line options](https://github.com/preemptive/PPiOS-Rename#command-line-argument-reference), we try to be pretty careful to indicate wrapping the argument to `-F` with single quotes (`'`) (so `-F '!FBS*'`, not `-F !FBS*`).  This will avoid possible interpretation of either the `!` or the `*` characters by the shell.

You should be able to see in the *PPiOS-Rename* output that your filters take effect.  For example, adding `-F '!FWDetele*'` to the configuration in the [sample project](https://github.com/preemptive/PPiOS-Sample-Vie), the output line:
```
2017-10-18 11:11:41.227 ppios-rename[54259:23990980] Adding @class FWDeleteButton
```
Becomes:
```
2017-10-18 11:12:35.363 ppios-rename[54407:23991843] Ignoring @class FWDeleteButton
```

This could be the issue, but I suspect something else is going on.  Make sure that `symbols.map` file that is used by the `ppios-rename --obfuscate-sources` command is the same that is produced by the `ppios-rename --analyze` step, e.g. that a stale file is not being used accidentally.

Another possibility for issues with Firebase or the Facebook SDK, is that libraries that they use need to be but are not being excluded.

If none of these suggestions solve your issue, we will need additional information, such as a few examples of the many errors you are seeing.

**Comment by renlix** [comment]
Very good, thank you for your help.Naw woks fine.
Thamk you very much.

**Comment by neuralmer** [comment]
Great!
